# .circleci/config.yml
version: 2.1

orbs:
  flutter: circleci/flutter@2.0.0

workflows:
  analyze-workflow:
    jobs:
      - flutter/lint:
          version: "3.7.3"
          app-dir: app/
      - flutter/unit_test:
          app-dir: app/
          version: "3.7.3"
      - flutter/unit_test:
          app-dir: packages/design_system
          version: "3.7.3"
      - flutter/unit_test:
          app-dir: packages/caching
          version: "3.7.3"
