name: votar
description: polling app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1

  design_system:
    path: ../packages/design_system
  caching:
    path: ../packages/caching

dev_dependencies:
  build_runner:
  riverpod_generator: ^1.1.1
  custom_lint:
  riverpod_lint:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-VariableFont_wght.ttf
        - asset: assets/fonts/Baloo_Bhaijaan_2/static/BalooBhaijaan2-Regular.ttf
          weight: 500
        - asset: assets/fonts/Baloo_Bhaijaan_2/static/BalooBhaijaan2-Medium.ttf
          weight: 600
        - asset: assets/fonts/Baloo_Bhaijaan_2/static/BalooBhaijaan2-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Baloo_Bhaijaan_2/static/BalooBhaijaan2-Bold.ttf
          weight: 800
        - asset: assets/fonts/Baloo_Bhaijaan_2/static/BalooBhaijaan2-ExtraBold.ttf
          weight: 900
