name: caching
description: Caching package includes simple and secure implmentation

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  shared_preferences: ^2.0.18

dev_dependencies:
  build_runner:
  custom_lint:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.1.1
  riverpod_lint:

flutter:
  uses-material-design: true
